import { createHash } from 'node:crypto';
import { mkdtemp, readFile, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { compileRegisteredBlock, planRegisteredBlockOutput } from '../src/authoring/generate.js';
import { inspectAuthoringDestination, writeGeneratedRegisteredBlock } from '../src/authoring/destination.js';
import type { AuthoringPlan } from '../src/authoring/schema.js';
import { PROOF_IMAGE_BASE64 } from '../src/proof/fixture-image.js';

async function fixture() {
  const root = await mkdtemp(path.join(tmpdir(), 'block-runner-asset-confirmation-'));
  const image = Buffer.from(PROOF_IMAGE_BASE64, 'base64');
  const source = path.join(root, 'source.png');
  await writeFile(source, image);
  const plan: AuthoringPlan = {
    version: 1, generatorVersion: '0.9.0', target: { name: 'acme/image', title: 'Image' },
    structure: [{ id: 'image', block: 'core/image', attributes: { alt: 'Product view' } }],
    fields: [], locking: { mode: 'contentOnly' }, pattern: { ready: false, overrides: [] },
    styles: { strategy: 'native', outcomes: [] }, warnings: [], files: [],
    assets: [{ id: 'product', source, destination: 'assets/product.png', status: 'ready',
      sha256: createHash('sha256').update(image).digest('hex'), uses: [{ node: 'image', attribute: 'url' }] }],
  };
  return { root, image, source, plan };
}

describe('confirmed bundled media', () => {
  it('refuses a mutated generated image before creating the destination', async () => {
    const { root, plan } = await fixture();
    const generated = compileRegisteredBlock(plan);
    generated.assets[0]!.content[0] = 0;
    await expect(writeGeneratedRegisteredBlock(path.join(root, 'output'), generated))
      .rejects.toThrow('Generated bytes or manifest changed');
    await expect(readFile(path.join(root, 'output/block.json'))).rejects.toMatchObject({ code: 'ENOENT' });
  });

  it('includes byte-exact assets in preview, manifest, generated editor imports, and the safe writer', async () => {
    const { root, image, plan } = await fixture();
    const output = path.join(root, 'output');
    const preview = planRegisteredBlockOutput(plan);
    expect(preview.files).toContainEqual({ path: 'assets/product.png', operation: 'create' });
    const inspection = await inspectAuthoringDestination(output, preview);
    const generated = compileRegisteredBlock(plan);
    expect(generated.assets[0]?.content).toEqual(image);
    expect(generated.manifest.files).toContainEqual(expect.objectContaining({ path: 'assets/product.png', contentHash: plan.assets[0]!.sha256 }));
    const edit = generated.files.find(({ path }) => path === 'edit.js')!.content;
    expect(edit).toContain('import asset0 from "./assets/product.png"');
    expect(edit).toContain('"url": asset0');
    expect(generated.template[0]?.[1]).not.toHaveProperty('id');
    await writeGeneratedRegisteredBlock(output, generated, inspection);
    expect(await readFile(path.join(output, 'assets/product.png'))).toEqual(image);
  });

  it('refuses changed source bytes before preview or compilation', async () => {
    const { source, plan } = await fixture();
    await writeFile(source, 'changed');
    expect(() => planRegisteredBlockOutput(plan)).toThrow('changed since confirmation');
    expect(() => compileRegisteredBlock(plan)).toThrow('changed since confirmation');
  });

  it('rejects symbolic sources, misleading media IDs, missing uses, and duplicate destinations', async () => {
    const { root, source, plan } = await fixture();
    const link = path.join(root, 'link.png');
    await symlink(source, link);
    expect(() => compileRegisteredBlock({ ...plan, assets: [{ ...plan.assets[0]!, source: link }] })).toThrow('not links');
    const withId = structuredClone(plan);
    withId.structure[0]!.attributes!.id = 123;
    expect(() => compileRegisteredBlock(withId)).toThrow('cannot-claim-media-id');
    expect(() => compileRegisteredBlock({ ...plan, assets: [{ ...plan.assets[0]!, uses: [] }] })).toThrow('declare its native image uses');
    expect(() => compileRegisteredBlock({ ...plan, assets: [...plan.assets, { ...plan.assets[0]!, id: 'duplicate', uses: [] }] })).toThrow('duplicate asset destination');
  });
});
