import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { expect, it } from 'vitest';
import { buildPatternOverridesFixture } from '../../scripts/build-pattern-overrides-fixture.js';
import { proveGutenbergCompatibility } from '../../scripts/proof-gutenberg-compat.mjs';
import { getWp } from '../../src/headless/wp.js';
import { PROOF_IMAGE_BASE64 } from '../../src/proof/fixture-image.js';

it('runs identical generated bytes through three isolated compatibility lanes', async () => {
  const outputDir = process.env.BLOCK_RUNNER_COMPAT_OUTPUT_DIR
    ? path.resolve(process.env.BLOCK_RUNNER_COMPAT_OUTPUT_DIR)
    : await mkdtemp(path.join(tmpdir(), 'block-runner-compat-'));
  await mkdir(outputDir, { recursive: true });
  process.stderr.write(`Compatibility evidence: ${outputDir}\n`);
  try {
    const built = await buildPatternOverridesFixture(path.join(outputDir, 'fixture'));
    const expectedTree = (await getWp()).parse(built.nativeContainerMarkup);
    const result = await proveGutenbergCompatibility({ root: process.cwd(), outputDir, built, expectedTree, imageBase64: PROOF_IMAGE_BASE64 });
    expect(result.status, JSON.stringify(result.lanes.map(({ name, status, error }) => ({ name, status, error })))).toBe('passed');
  } catch (error) {
    await writeFile(path.join(outputDir, 'failure.json'), JSON.stringify({ status: 'failed', error: String(error) }, null, 2));
    throw error;
  }
}, 1_800_000);
