/**
 * Receipt-backed release-candidate evidence runner.
 *
 * Each command writes immutable stdout/stderr artifacts. ZIP activation is run
 * through the production WordPress 7.1 proof CLI and additionally checks the
 * generated ZIP, activation result, block registration, and retained logs.
 */
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { register } from 'tsx/esm/api';

register();
const { evaluateReleaseAcceptance, loadNativeHeadingControlEvidence, summarizeReleaseAcceptance } =
  await import('../src/proof/release-acceptance.ts');

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const selected = valueFor('--matrix') ?? 'full-release-matrix';
const requestedReceipt = valueFor('--receipt');
const startedAt = new Date().toISOString();
const startedMs = performance.now();
const rows = [];
let packed;
let pluginZip;
let activation;

const allowed = new Set(['full-release-matrix', 'package-packed', 'skill-validate', 'skill-project-install', 'skill-user-install', 'zip-activation']);
if (!allowed.has(selected)) throw new Error(`unknown --matrix value ${JSON.stringify(selected)}`);

const receiptFile = requestedReceipt
  ? path.resolve(ROOT, requestedReceipt)
  : path.join(mkdtempSync(path.join(tmpdir(), 'block-runner-release-receipt-')), 'receipt.json');
const evidenceDirectory = `${receiptFile}.artifacts`;
if (requestedReceipt && existsSync(receiptFile)) throw new Error(`refusing to overwrite immutable release receipt: ${receiptFile}`);
if (existsSync(evidenceDirectory)) throw new Error(`refusing to overwrite immutable release evidence: ${evidenceDirectory}`);
mkdirSync(evidenceDirectory, { recursive: true });

try {
  if (selected === 'full-release-matrix') {
    runRow('candidate-verify', 'npm', ['run', 'verify']);
    const plans = valueFor('--plans');
    if (plans) {
      const authoring = runRow('authoring-wordpress-71-proof', 'npm', ['run', 'authoring:prove', '--', '--plans', path.resolve(plans)]);
      authoring.releaseRequired = false;
    }
    else pendingRow('authoring-wordpress-71-proof', 'authoring:prove', 'Optional authoring benchmark remains pending: supply saved canonical candidate plans with --plans to run it. No model calls or placeholder candidates are generated by this release check.');
  }
  if (selected === 'full-release-matrix' || selected === 'package-packed') {
    packed = packCandidate();
    if (packed) installPackedCandidate(packed);
  }
  if (selected === 'full-release-matrix' || selected === 'skill-validate') validateCanonicalSkill();
  if (selected === 'full-release-matrix' || selected === 'skill-project-install') {
    const candidate = packed ?? packCandidate();
    if (candidate) installProjectSkill(candidate);
  }
  if (selected === 'full-release-matrix' || selected === 'skill-user-install') {
    const candidate = packed ?? packCandidate();
    if (candidate) installUserSkill(candidate);
  }
  if (selected === 'full-release-matrix' || selected === 'zip-activation') {
    activation = activateGeneratedPluginZip();
    if (selected === 'full-release-matrix') recordFullProofAcceptance();
  }
} catch (error) {
  rows.push({
    id: 'release-runner', status: 'engine_error', command: 'release-check internal orchestration', elapsedMs: 0,
    detail: error instanceof Error ? error.message : String(error), artifacts: retainLogs('release-runner', '', error instanceof Error ? error.stack ?? error.message : String(error)),
  });
}

const receipt = buildReceipt();
const schemaFailures = validateReleaseReceipt(receipt);
if (schemaFailures.length) {
  receipt.status = 'engine_error';
  receipt.measurement.engineError = `release receipt schema validation failed: ${schemaFailures.join('; ')}`;
}
const rowResults = path.join(evidenceDirectory, 'row-results.json');
writeFileSync(rowResults, `${JSON.stringify(rows, null, 2)}\n`, 'utf8');
receipt.artifacts.retained.push(relativeArtifact(rowResults));
writeFileSync(receiptFile, `${JSON.stringify(receipt, null, 2)}\n`, 'utf8');
process.stdout.write(`${JSON.stringify(receipt, null, 2)}\n`);
if (receipt.status !== 'passed') process.exitCode = 1;

function valueFor(flag) {
  const index = process.argv.indexOf(flag);
  if (index < 0) return undefined;
  const value = process.argv[index + 1];
  if (!value || value.startsWith('--')) throw new Error(`${flag} requires a value`);
  return value;
}

function hash(value) { return `sha256:${createHash('sha256').update(value).digest('hex')}`; }
function hashFile(file) { return hash(readFileSync(file)); }
function canonicalJson(value) {
  if (value === undefined) return 'undefined';
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(',')}]`;
  return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(',')}}`;
}
function filesBelow(directory) {
  if (!existsSync(directory)) return [];
  return readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name)).flatMap((entry) => {
    const file = path.join(directory, entry.name);
    return entry.isDirectory() ? filesBelow(file) : entry.isFile() ? [file] : [];
  });
}
function treeHash(directory, include = () => true) {
  const files = filesBelow(directory).map((file) => path.relative(directory, file).split(path.sep).join('/')).filter(include).sort()
    .map((relative) => ({ path: relative, sha256: hashFile(path.join(directory, relative)).replace(/^sha256:/, '') }));
  return hash(canonicalJson(files));
}
function relativeArtifact(file) { return path.relative(path.dirname(receiptFile), file).split(path.sep).join('/'); }
function retainLogs(id, stdout, stderr) {
  const logs = path.join(evidenceDirectory, 'logs');
  const stdoutFile = path.join(logs, `${id}.stdout.log`);
  const stderrFile = path.join(logs, `${id}.stderr.log`);
  mkdirSync(logs, { recursive: true });
  writeFileSync(stdoutFile, stdout ?? '', 'utf8');
  writeFileSync(stderrFile, stderr ?? '', 'utf8');
  return { stdout: { path: relativeArtifact(stdoutFile), sha256: hashFile(stdoutFile) }, stderr: { path: relativeArtifact(stderrFile), sha256: hashFile(stderrFile) } };
}

function runRow(id, command, args, options = {}) {
  const start = performance.now();
  const result = spawnSync(command, args, { cwd: ROOT, encoding: 'utf8', env: process.env, ...options });
  const row = {
    id, status: result.error ? 'engine_error' : result.status === 0 ? 'passed' : 'failed', command: [command, ...args].join(' '),
    elapsedMs: Math.round(performance.now() - start), detail: result.error?.message ?? (result.status === 0 ? undefined : `exit ${result.status ?? 'unknown'}`),
    artifacts: retainLogs(id, result.stdout ?? '', result.stderr ?? result.error?.message ?? ''),
  };
  rows.push(row);
  if (result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);
  return row;
}
function blockedRow(id, command, detail) {
  rows.push({ id, status: 'blocked', command, elapsedMs: 0, detail, artifacts: retainLogs(id, '', detail) });
  return undefined;
}
function pendingRow(id, command, detail) {
  rows.push({ id, status: 'pending', releaseRequired: false, command, elapsedMs: 0, detail, artifacts: retainLogs(id, '', detail) });
  return undefined;
}

function packCandidate() {
  const directory = mkdtempSync(path.join(tmpdir(), 'block-runner-rc-pack-'));
  if (runRow('candidate-package-dry-run', 'npm', ['run', 'pack:check']).status !== 'passed') return undefined;
  const row = runRow('candidate-package-artifact', 'npm', ['pack', '--json', '--ignore-scripts', '--pack-destination', directory]);
  if (row.status !== 'passed') return undefined;
  const tarballs = filesBelow(directory).filter((file) => file.endsWith('.tgz'));
  if (tarballs.length !== 1) { row.status = 'failed'; row.detail = `expected exactly one npm tarball, found ${tarballs.length}`; return undefined; }
  const retained = path.join(evidenceDirectory, 'artifacts', path.basename(tarballs[0]));
  mkdirSync(path.dirname(retained), { recursive: true });
  copyFileSync(tarballs[0], retained);
  row.artifact = { path: relativeArtifact(retained), sha256: hashFile(retained) };
  return { tarball: tarballs[0], sha256: row.artifact.sha256 };
}
function installPackedCandidate(candidate, rowId = 'packed-candidate-smoke') {
  const consumer = mkdtempSync(path.join(tmpdir(), 'block-runner-rc-consumer-'));
  const row = runRow(rowId, 'npm', ['install', '--ignore-scripts', '--no-audit', '--no-fund', candidate.tarball], { cwd: consumer });
  const cli = path.join(consumer, 'node_modules', 'block-runner', 'dist', 'cli.js');
  if (row.status === 'passed' && !existsSync(cli)) { row.status = 'failed'; row.detail = `packed CLI missing: ${cli}`; }
  if (row.status === 'passed') {
    const smoke = runRow(`packed-candidate-runtime-${rows.length}`, process.execPath, ['--input-type=module', '-e',
      "import { convert, author, compileAuthoringPlan } from 'block-runner'; import { createRequire } from 'node:module'; import { execFileSync } from 'node:child_process'; const require=createRequire(import.meta.url); const pkg=require('block-runner/package.json'); if (![convert,author,compileAuthoringPlan].every(fn=>typeof fn==='function')) throw new Error('Missing public exports'); const actual=execFileSync(process.execPath,[process.argv[1],'--version'],{encoding:'utf8'}).trim(); if(actual!==pkg.version) throw new Error('CLI version mismatch'); console.log(JSON.stringify({version:actual,exports:'ok'}));", cli], { cwd: consumer });
    if (smoke.status !== 'passed') { row.status = 'failed'; row.detail = 'Packed CLI or ESM consumer failed.'; }
  }
  return { consumer, cli };
}
function validateCanonicalSkill() {
  runRow('canonical-skill-validation', process.execPath, [path.join(ROOT, 'dist', 'cli.js'), 'skill', '--install', '--dry-run', '--dir', mkdtempSync(path.join(tmpdir(), 'block-runner-skill-validate-'))]);
}
function installProjectSkill(candidate) {
  const { consumer, cli } = installPackedCandidate(candidate, 'project-skill-package-install');
  const project = path.join(consumer, 'project'); mkdirSync(project);
  const row = runRow('project-skill-installer-smoke', process.execPath, [cli, 'skill', '--install'], { cwd: project });
  if (row.status === 'passed') {
    try {
      const bundle = path.join(consumer, 'node_modules', 'block-runner', 'skills', 'block-runner');
      for (const target of ['.agents', '.claude']) validateInstalledSkill(path.join(project, target, 'skills', 'block-runner'), bundle);
      const before = treeHash(project);
      const repeat = runRow('project-skill-installer-idempotence', process.execPath, [cli, 'skill', '--install'], { cwd: project });
      if (repeat.status !== 'passed' || before !== treeHash(project)) throw new Error('Second skill install failed or changed the installed files.');
    } catch (error) { row.status = 'failed'; row.detail = error.message; }
  }
}
function installUserSkill(candidate) {
  const { consumer, cli } = installPackedCandidate(candidate, 'user-skill-package-install');
  const home = path.join(consumer, 'home'); const project = path.join(consumer, 'project'); mkdirSync(home); mkdirSync(project);
  const row = runRow('user-skill-installer-smoke', process.execPath, [cli, 'skill', '--install', '--scope', 'user', '--target', 'agents'], { cwd: project, env: { ...process.env, HOME: home } });
  if (row.status === 'passed') {
    try {
      validateInstalledSkill(path.join(home, '.agents', 'skills', 'block-runner'), path.join(consumer, 'node_modules', 'block-runner', 'skills', 'block-runner'));
      if (existsSync(path.join(home, '.claude')) || filesBelow(project).length) throw new Error('User-target skill install wrote outside the selected target.');
    } catch (error) { row.status = 'failed'; row.detail = error.message; }
  }
}

function validateInstalledSkill(destination, bundle) {
  const manifest = JSON.parse(readFileSync(path.join(destination, '.block-runner-install.json'), 'utf8'));
  const version = JSON.parse(readFileSync(path.resolve(bundle, '../../package.json'), 'utf8')).version;
  if (manifest.packageVersion !== version) throw new Error('Installed skill version does not match the packed package.');
  const names = filesBelow(bundle).map((file) => path.relative(bundle, file).split(path.sep).join('/')).sort();
  if (JSON.stringify(Object.keys(manifest.files ?? {}).sort()) !== JSON.stringify(names)) throw new Error('Installed skill manifest does not describe the packed bundle.');
  for (const name of names) {
    const bytes = readFileSync(path.join(bundle, name));
    const expected = hash(name.endsWith('.md') ? bytes.toString('utf8').replace(/block-runner@latest(?!\s+skill\b)/g, `block-runner@${version}`) : bytes);
    if (manifest.files[name].sha256 !== expected || hashFile(path.join(destination, name)) !== expected) {
      throw new Error(`Installed skill hash mismatch: ${name}`);
    }
  }
}

function createGeneratedPluginZip() {
  const root = path.join(evidenceDirectory, 'generated-plugin');
  const row = runRow('generated-plugin-zip', process.execPath,
    ['--import', 'tsx', path.join(ROOT, 'scripts/build-pattern-overrides-fixture.ts'), root]);
  if (row.status !== 'passed') return undefined;
  const built = JSON.parse(readFileSync(path.resolve(path.dirname(receiptFile), row.artifacts.stdout.path), 'utf8'));
  if (!built.pluginZip || !existsSync(built.pluginZip)) throw new Error('Production fixture builder did not emit a ZIP.');
  row.artifact = { path: relativeArtifact(built.pluginZip), sha256: hashFile(built.pluginZip) };
  return { ...built, zip: built.pluginZip, sha256: row.artifact.sha256,
    sourceHash: treeHash(path.join(path.dirname(built.pluginZip), 'src')) };
}

function activateGeneratedPluginZip() {
  pluginZip = createGeneratedPluginZip();
  if (!pluginZip) return undefined;
  const manualReview = valueFor('--manual-review');
  if (manualReview) {
    const reviewPath = path.resolve(manualReview);
    const review = JSON.parse(readFileSync(reviewPath, 'utf8'));
    validateManualReviewBinding(review, hashFile(pluginZip.inputPath), pluginZip.sha256);
    const fixture = JSON.parse(readFileSync(pluginZip.fixture, 'utf8'));
    fixture.accessibility = { ...fixture.accessibility, manualReviewPath: reviewPath };
    writeFileSync(pluginZip.fixture, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8');
  }
  const work = path.join(evidenceDirectory, 'wordpress-proof');
  const row = runRow('generated-plugin-zip-activation', process.execPath, [
    '--import', 'tsx', path.join(ROOT, 'src/cli.ts'), 'proof', pluginZip.zip,
    '--profile', 'full', '--input', pluginZip.inputPath,
    '--markup', pluginZip.nativeContainerMarkup, '--fixture', pluginZip.fixture,
    '--receipt-dir', work, '--json',
  ], { timeout: 600_000 });
  try {
    const proof = JSON.parse(readFileSync(path.resolve(path.dirname(receiptFile), row.artifacts.stdout.path), 'utf8'));
    const receipt = proof.receipt;
    const observed = validateGeneratedPluginActivation(receipt, pluginZip.sha256);
    const acceptance = summarizeReleaseAcceptance(evaluateReleaseAcceptance(receipt, {
      nativeHeadingControlEvidence: retainNativeHeadingControlEvidence(),
    }));
    const acceptanceFile = path.join(work, 'release-acceptance.json');
    writeFileSync(acceptanceFile, `${JSON.stringify(acceptance, null, 2)}\n`, 'utf8');
    // This row claims ZIP activation only. Preserve the entire full-profile
    // receipt, including failed or blocked visual/accessibility gates.
    row.status = 'passed';
    row.detail = proof.ok
      ? 'ZIP activation gates passed; the full-profile receipt is retained.'
      : 'ZIP activation gates passed; full-profile limitations remain in the retained receipt.';
    const retainedLogs = filesBelow(work).map((file) => ({ path: relativeArtifact(file), sha256: hashFile(file) }));
    row.activation = {
      pluginZipHash: pluginZip.sha256,
      logs: retainedLogs,
      registeredBlock: 'block-runner/pattern-overrides-fixture',
      acceptance,
      acceptanceArtifact: { path: relativeArtifact(acceptanceFile), sha256: hashFile(acceptanceFile) },
    };
    return { result: { environment: {
      wordpress: observed.wordpress.version, wordpressHash: observed.wordpress.coreHash,
      theme: observed.theme.name, themeHash: observed.theme.fileHash,
      browser: observed.browser.version, browserHash: hash(canonicalJson(observed.browser)),
      driver: 'Block Runner production WordPress proof CLI',
    } }, retainedLogs, acceptance, acceptanceArtifact: row.activation.acceptanceArtifact, rowArtifacts: row.artifacts };
  } catch (error) {
    row.status = 'failed';
    row.detail = error instanceof Error ? error.message : String(error);
    return undefined;
  }
}

function validateManualReviewBinding(review, inputHash, pluginZipHash) {
  if (!review || review.inputHash !== inputHash || review.pluginZipHash !== pluginZipHash) {
    throw new Error('Manual review describes a different generated input or plugin ZIP; review this candidate before release.');
  }
  // The production proof reader validates the complete review and retains its
  // bytes. This early check prevents an expensive run against stale evidence.
}

/**
 * Copy a separately run native Heading control into this receipt's immutable
 * evidence directory. Without all three environment values, the exception is
 * deliberately unavailable and the raw Heading failure remains a blocker.
 */
function retainNativeHeadingControlEvidence() {
  const sourceValue = process.env.BLOCK_RUNNER_NATIVE_HEADING_CONTROL_EVIDENCE_PATH;
  const declaredHash = process.env.BLOCK_RUNNER_NATIVE_HEADING_CONTROL_EVIDENCE_SHA256;
  const wordpressVersion = process.env.BLOCK_RUNNER_NATIVE_HEADING_CONTROL_WORDPRESS_VERSION;
  if (!sourceValue && !declaredHash && !wordpressVersion) return undefined;
  if (!sourceValue || !declaredHash || !wordpressVersion) throw new Error('native Heading exception requires evidence path, SHA-256, and observed WordPress version');
  const source = path.resolve(sourceValue);
  if (!existsSync(source)) throw new Error(`native Heading control evidence is missing: ${source}`);
  const actualHash = hashFile(source);
  if (actualHash !== declaredHash) throw new Error(`native Heading control evidence hash mismatch: declared ${declaredHash}, observed ${actualHash}`);
  const destination = path.join(evidenceDirectory, 'control', 'native-heading-control.json');
  mkdirSync(path.dirname(destination), { recursive: true });
  copyFileSync(source, destination);
  const loaded = loadNativeHeadingControlEvidence({
    wordpressVersion,
    evidence: { path: destination, sha256: actualHash },
  });
  return { ...loaded, evidence: { path: relativeArtifact(destination), sha256: actualHash } };
}

function recordFullProofAcceptance() {
  const acceptance = activation?.acceptance;
  const activationRow = rows.find((item) => item.id === 'generated-plugin-zip-activation');
  if (!acceptance || !activationRow) {
    blockedRow(
      'generated-plugin-full-proof-acceptance',
      'full WordPress 7.1 proof acceptance',
      'The generated plugin proof did not produce a release-acceptance assessment.',
    );
    return;
  }
  rows.push({
    id: 'generated-plugin-full-proof-acceptance',
    status: acceptance.releaseStatus,
    command: 'full WordPress 7.1 proof + approved-exception/manual acceptance',
    elapsedMs: 0,
    detail: acceptance.releaseOk
      ? 'Full WordPress proof is releasable.'
      : `Full-profile release blockers remain: ${acceptance.releaseBlockers.map(({ gate, status }) => `${gate}:${status}`).join(', ')}`,
    artifacts: activationRow.artifacts,
    acceptanceArtifact: activation.acceptanceArtifact?.path,
  });
}

function validateGeneratedPluginActivation(receipt, zipHash) {
  const observed = receipt?.environment;
  const required = ['zip_installation', 'plugin_activation', 'php_registry', 'rest_block_type',
    'client_registry', 'editor_inserter', 'php_logs', 'environment_observation'];
  if (observed?.plugin?.zip?.sha256 !== zipHash
    || !/^7\.1(?:\.\d+)?$/.test(observed?.wordpress?.version ?? '')
    || !required.every((gate) => receipt.gates?.filter((result) => result.gate === gate).length === 1
      && receipt.gates.some((result) => result.gate === gate && result.status === 'pass'))
    || !receipt.gates.some((result) => result.gate === 'client_registry'
      && result.details?.block === 'block-runner/pattern-overrides-fixture')) {
    throw new Error('Production proof did not verify the exact generated ZIP, registration, inserter, environment, and PHP logs.');
  }
  return observed;
}

function gitValue(args, fallback) { const result = spawnSync('git', args, { cwd: ROOT, encoding: 'utf8' }); return result.status === 0 && result.stdout.trim() ? result.stdout.trim() : fallback; }
function authoringProvenance() {
  const directory = path.join(ROOT, 'benchmarks', 'authoring');
  const corpusHash = treeHash(directory, (relative) => relative !== 'hashes.json' && !relative.startsWith('runs/'));
  const fixtureManifestHash = treeHash(directory, (relative) => relative === 'fixtures.json' || relative === 'suite.json' || relative === 'schema.json' || relative.startsWith('fixtures/'));
  const sourceSetHash = treeHash(directory, (relative) => relative.startsWith('sources/'));
  const fixtures = JSON.parse(readFileSync(path.join(directory, 'fixtures.json'), 'utf8')).fixtures;
  const sourceDependencyHash = hash(canonicalJson(fixtures.map((fixture) => ({
    id: fixture.id,
    dependencies: [fixture.source, ...(Array.isArray(fixture.sourceDependencies) ? fixture.sourceDependencies : [])]
      .filter(Boolean)
      .map((dependency) => {
        const relative = typeof dependency.path === 'string' ? dependency.path : '';
        return { path: relative, declaredHash: dependency.sha256, actualHash: hashFile(path.resolve(directory, relative)) };
      }),
  }))));
  const expectedPlanHash = treeHash(directory, (relative) => relative.endsWith('/expected-plan.json'));
  const manifest = JSON.parse(readFileSync(path.join(directory, 'hashes.json'), 'utf8'));
  if (manifest.values?.suiteHash?.value !== corpusHash.replace(/^sha256:/, '')) throw new Error('benchmarks/authoring/hashes.json suiteHash is stale');
  const environment = activation?.result?.environment ?? {};
  return { suiteHash: corpusHash, corpusHash, scorerHash: hash(canonicalJson({ scorer: hashFile(path.join(ROOT, 'scripts', 'authoring', 'score.ts')), runner: hashFile(path.join(ROOT, 'scripts', 'authoring-runner.ts')) })), fixtureManifestHash, sourceSetHash, sourceDependencyHash, expectedPlanHash, promptGuideHash: hash(canonicalJson([hashFile(path.join(directory, 'contract.md')), hashFile(path.join(directory, 'README.md')), treeHash(path.join(directory, 'fixtures'), (relative) => relative.endsWith('/prompt.md'))])), templateHash: hash(canonicalJson({ compiler: treeHash(path.join(ROOT, 'src/authoring')), plugin: hashFile(path.join(ROOT, 'src/plugin/profile.ts')) })), dependencyHash: hashFile(path.join(ROOT, 'package-lock.json')), wordpressHash: environment.wordpressHash ?? null, themeHash: environment.themeHash ?? null, browserHash: environment.browserHash ?? null, generatedSourceHash: pluginZip?.sourceHash ?? null };
}
function gateFor(...ids) { const row = ids.map((id) => rows.find((item) => item.id === id && item.releaseRequired !== false)).find(Boolean); return { state: row?.status ?? 'blocked', evidence: row?.artifacts?.stdout?.path ?? relativeArtifact(path.join(evidenceDirectory, 'row-results.json')), detail: row?.detail }; }
function buildReceipt() {
  const pkg = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  const releaseRows = rows.filter((row) => row.releaseRequired !== false);
  const statuses = releaseRows.map((row) => row.status);
  const candidateCommit = gitValue(['rev-parse', 'HEAD'], '0000000');
  const worktreeClean = gitValue(['status', '--porcelain'], '') === '';
  let status = statuses.includes('engine_error') ? 'engine_error' : statuses.includes('failed') ? 'failed' : statuses.includes('blocked') ? 'blocked' : statuses.length ? 'passed' : 'blocked';
  // A passing release-candidate receipt must identify a clean committed tree.
  // Keep dirty local diagnostics useful, but do not let them be mistaken for
  // evidence of the commit that will actually be published.
  if (status === 'passed' && ['full-release-matrix', 'package-packed', 'zip-activation'].includes(selected) && !worktreeClean) status = 'blocked';
  const retained = rows.flatMap((row) => [row.artifacts?.stdout?.path, row.artifacts?.stderr?.path, row.artifact?.path, row.acceptanceArtifact, ...(row.activation?.logs?.map((log) => log.path) ?? [])].filter(Boolean));
  const acceptance = activation?.acceptance;
  const acceptanceGate = acceptance
    ? {
      state: acceptance.releaseOk ? 'passed' : acceptance.releaseStatus,
      evidence: activation.acceptanceArtifact?.path ?? relativeArtifact(path.join(evidenceDirectory, 'row-results.json')),
      detail: acceptance.releaseOk ? 'Full proof accepted.' : `Full-proof limitations: ${acceptance.releaseBlockers.map(({ gate, status }) => `${gate}:${status}`).join(', ')}`,
    }
    : gateFor('generated-plugin-full-proof-acceptance', 'authoring-wordpress-71-proof', 'generated-plugin-zip-activation');
  const authoringProof = rows.find((row) => row.id === 'authoring-wordpress-71-proof');
  const benchmarkReadiness = {
    // The optional authoring proof is not a measured model benchmark. Keep its
    // readiness pending until a separate benchmark receipt is scored; never
    // let a passing proof command become a benchmark claim by implication.
    status: authoringProof?.status === 'failed' || authoringProof?.status === 'blocked' || authoringProof?.status === 'engine_error'
      ? authoringProof.status
      : 'pending',
    scored: false,
    requiredForRelease: false,
    proofStatus: authoringProof?.status ?? 'pending',
    command: authoringProof?.command ?? 'npm run authoring:prove -- --plans <saved-canonical-plans>',
    detail: authoringProof?.detail ?? 'Optional registered-block authoring benchmark was not selected for this release-check run.',
    evidence: authoringProof?.artifacts?.stdout?.path ?? relativeArtifact(path.join(evidenceDirectory, 'row-results.json')),
  };
  return {
    schemaVersion: 1, receiptId: `rc.1-${selected}-${startedAt.replace(/[:.]/g, '-')}`, matrixRowId: selected, status, measurementState: 'not_applicable', startedAt, finishedAt: new Date().toISOString(), command: `npm run release:check -- --matrix ${selected}`,
    candidate: { commit: candidateCommit, packageVersion: pkg.version, worktreeClean },
    provenance: { ...authoringProvenance(), model: process.env.BLOCK_RUNNER_MODEL ?? 'deterministic release harness', effort: process.env.BLOCK_RUNNER_EFFORT ?? 'not applicable' },
    environment: { os: `${process.platform}-${process.arch}`, node: process.version, npm: spawnSync('npm', ['--version'], { encoding: 'utf8' }).stdout?.trim() || 'unavailable', wordpress: '7.1', theme: activation?.result?.environment?.theme ?? 'unverified WordPress fixture theme', browser: activation?.result?.environment?.browser ?? 'unverified browser', driver: activation?.result?.environment?.driver ?? 'unverified fixture driver' },
    timing: { elapsedMs: Math.round(performance.now() - startedMs), method: 'monotonic wall-clock from release-check start through immutable receipt write', timeoutMs: Number(process.env.BLOCK_RUNNER_RELEASE_TIMEOUT_MS ?? 900000) },
    artifacts: { npmTarballHash: packed?.sha256, pluginZipHash: pluginZip?.sha256, stdoutHash: hash(canonicalJson(rows.map((row) => row.artifacts?.stdout?.sha256 ?? ''))), stderrHash: hash(canonicalJson(rows.map((row) => row.artifacts?.stderr?.sha256 ?? ''))), retained: [...new Set(retained.length ? retained : [relativeArtifact(path.join(evidenceDirectory, 'row-results.json'))])] },
    ...(acceptance ? { acceptance } : {}),
    benchmarkReadiness,
    gates: { build: gateFor('candidate-verify'), editor: acceptanceGate, frontend: acceptanceGate, pattern: acceptanceGate, fidelity: acceptanceGate, accessibility: acceptanceGate },
    measurement: { suiteSize: 13, workload: '0.9 release candidate matrix; optional authoring benchmark is reported separately', invalidCount: statuses.filter((value) => value === 'blocked' || value === 'engine_error').length, warnings: [...(worktreeClean ? [] : ['candidate tree has uncommitted changes; this receipt is diagnostic and cannot certify a release commit']), ...(benchmarkReadiness.status === 'pending' ? ['optional registered-block authoring benchmark remains pending and produced no score'] : [])] },
  };
}
function validateReleaseReceipt(receipt) {
  const failures = []; const required = ['schemaVersion', 'receiptId', 'matrixRowId', 'status', 'measurementState', 'startedAt', 'finishedAt', 'command', 'candidate', 'provenance', 'environment', 'timing', 'artifacts', 'gates'];
  for (const key of required) if (!(key in receipt)) failures.push(`missing ${key}`);
  for (const key of Object.keys(receipt)) if (!new Set([...required, 'supersedes', 'measurement', 'acceptance', 'benchmarkReadiness']).has(key)) failures.push(`unsupported top-level field ${key}`);
  if (receipt.schemaVersion !== 1 || !['passed', 'failed', 'unsupported', 'blocked', 'engine_error'].includes(receipt.status) || !['scored', 'unsupported', 'blocked', 'engine_error', 'not_applicable'].includes(receipt.measurementState)) failures.push('invalid receipt status fields');
  if (!/^0\.9\.0(?:[-+][0-9A-Za-z.-]+)?$/.test(receipt.candidate?.packageVersion ?? '') || !/^[0-9a-f]{7,64}$/.test(receipt.candidate?.commit ?? '') || typeof receipt.candidate?.worktreeClean !== 'boolean') failures.push('invalid candidate identity');
  for (const key of ['suiteHash', 'corpusHash', 'scorerHash', 'fixtureManifestHash', 'sourceSetHash', 'sourceDependencyHash', 'expectedPlanHash', 'promptGuideHash', 'templateHash', 'dependencyHash']) if (!/^sha256:[0-9a-f]{64}$/.test(receipt.provenance?.[key] ?? '')) failures.push(`invalid provenance ${key}`);
  for (const key of ['wordpressHash', 'themeHash', 'browserHash', 'generatedSourceHash']) {
    const value = receipt.provenance?.[key];
    const required = receipt.status === 'passed' && ['full-release-matrix', 'zip-activation'].includes(receipt.matrixRowId);
    if (!(value === null && !required) && !/^sha256:[0-9a-f]{64}$/.test(value ?? '')) failures.push(`invalid observed provenance ${key}`);
  }
  if (receipt.environment?.wordpress !== '7.1') failures.push('receipt environment must target WordPress 7.1');
  for (const key of ['os', 'node', 'npm', 'theme', 'browser', 'driver']) if (typeof receipt.environment?.[key] !== 'string' || !receipt.environment[key]) failures.push(`missing environment ${key}`);
  if (!Number.isInteger(receipt.timing?.elapsedMs) || receipt.timing.elapsedMs < 0 || !Number.isInteger(receipt.timing?.timeoutMs) || receipt.timing.timeoutMs < 1) failures.push('invalid timing');
  for (const key of ['stdoutHash', 'stderrHash']) if (!/^sha256:[0-9a-f]{64}$/.test(receipt.artifacts?.[key] ?? '')) failures.push(`invalid artifacts ${key}`);
  if (!Array.isArray(receipt.artifacts?.retained) || !receipt.artifacts.retained.length) failures.push('missing retained artifacts');
  for (const key of ['build', 'editor', 'frontend', 'pattern', 'fidelity', 'accessibility']) { const gate = receipt.gates?.[key]; if (!gate || !['passed', 'failed', 'unsupported', 'blocked', 'engine_error'].includes(gate.state) || typeof gate.evidence !== 'string' || !gate.evidence) failures.push(`invalid gate ${key}`); }
  if (receipt.acceptance !== undefined) {
    const acceptance = receipt.acceptance;
    if (!acceptance || typeof acceptance !== 'object') failures.push('invalid acceptance summary');
    else {
      for (const key of ['rawProfileOk', 'automatedOk', 'releaseOk']) if (typeof acceptance[key] !== 'boolean') failures.push(`invalid acceptance ${key}`);
      if (!['passed', 'failed', 'blocked', 'engine_error'].includes(acceptance.releaseStatus)) failures.push('invalid acceptance releaseStatus');
      for (const key of ['rawFailures', 'automatedBlockers', 'releaseBlockers', 'acceptedUpstreamFindings']) if (!Array.isArray(acceptance[key])) failures.push(`invalid acceptance ${key}`);
    }
  }
  if (receipt.benchmarkReadiness !== undefined) {
    const benchmark = receipt.benchmarkReadiness;
    if (!benchmark || typeof benchmark !== 'object') failures.push('invalid benchmarkReadiness');
    else {
      if (!['pending', 'failed', 'blocked', 'engine_error'].includes(benchmark.status)) failures.push('invalid benchmarkReadiness status');
      if (benchmark.scored !== false || benchmark.requiredForRelease !== false) failures.push('optional benchmark must remain unscored and non-blocking');
      if (!['pending', 'passed', 'failed', 'blocked', 'engine_error'].includes(benchmark.proofStatus)) failures.push('invalid benchmarkReadiness proofStatus');
      if (typeof benchmark.command !== 'string' || !benchmark.command) failures.push('invalid benchmarkReadiness command');
      if (typeof benchmark.detail !== 'string' || !benchmark.detail) failures.push('invalid benchmarkReadiness detail');
      if (typeof benchmark.evidence !== 'string' || !benchmark.evidence) failures.push('invalid benchmarkReadiness evidence');
    }
  }
  if (receipt.status === 'passed' && receipt.matrixRowId === 'full-release-matrix'
    && (!receipt.acceptance || receipt.acceptance.releaseOk !== true)) failures.push('full release matrix passed without full-proof release acceptance');
  if (receipt.status === 'passed' && ['full-release-matrix', 'package-packed', 'zip-activation'].includes(receipt.matrixRowId)
    && receipt.candidate?.worktreeClean !== true) failures.push('release candidate receipt passed from a dirty worktree');
  if (receipt.matrixRowId === 'zip-activation' && receipt.status === 'passed' && !receipt.acceptance) failures.push('ZIP activation receipt is missing the retained full-proof acceptance assessment');
  return failures;
}
