import type { AuthoringFile, AuthoringPlan, AuthoringStructureNode, JsonValue } from './schema.js';

/**
 * Derive the executable files from the declarative plan. This is deliberately invoked only after
 * confirmation: the plan remains reviewable JSON and never needs to contain implementation text.
 * Supplied file content is retained for callers that have an independently materialized asset.
 */
export function materializeAuthoringPlan(plan: AuthoringPlan): AuthoringPlan {
  const files = plan.files.map((file) => file.content === undefined
    ? { ...file, content: generatedFile(file, plan) }
    : file);
  return { ...plan, files };
}

function generatedFile(file: AuthoringFile, plan: AuthoringPlan): string {
  if (file.path === 'block.json' || file.kind === 'metadata') {
    return `${JSON.stringify(blockMetadata(plan), null, 2)}\n`;
  }
  if (file.kind === 'editor' || /(?:^|\/)(?:index|editor)\.(?:[cm]?[jt]sx?)$/.test(file.path)) {
    return editorSource(plan, file.path);
  }
  if (file.kind === 'style' || file.path.endsWith('.css')) {
    return styleSource(plan);
  }
  throw new Error(`authoring plan cannot deterministically generate ${JSON.stringify(file.path)}; use a metadata, editor, or style file kind`);
}

function blockMetadata(plan: AuthoringPlan): Record<string, JsonValue> {
  const editor = plan.files.find((file) => file.kind === 'editor'
    || /(?:^|\/)(?:index|editor)\.(?:[cm]?[jt]sx?)$/.test(file.path));
  const style = plan.files.find((file) => file.kind === 'style' || file.path.endsWith('.css'));
  const metadata: Record<string, JsonValue> = {
    '$schema': 'https://schemas.wp.org/trunk/block.json',
    apiVersion: 3,
    name: plan.target.name,
    title: plan.target.title,
    category: plan.target.category ?? 'widgets',
    textdomain: plan.target.textDomain ?? plan.target.name.split('/')[0]!,
    supports: { html: false },
  };
  if (plan.target.description) metadata.description = plan.target.description;
  if (plan.target.icon) metadata.icon = plan.target.icon;
  if (editor) metadata.editorScript = `file:./${editor.path}`;
  if (style) metadata.style = `file:./${style.path}`;
  return metadata;
}

function editorSource(plan: AuthoringPlan, outputPath: string): string {
  const template = plan.structure.map(templateNode);
  const lock = plan.locking.mode === 'none' ? false : plan.locking.mode;
  const allowedBlocks = uniqueBlocks(plan.structure);
  const depth = outputPath.split('/').length - 1;
  const metadataImport = depth === 0 ? './block.json' : `${'../'.repeat(depth)}block.json`;
  return `/* Generated by Block Runner from AuthoringPlan v${plan.version}. */
import { registerBlockType } from '@wordpress/blocks';
import { InnerBlocks, useBlockProps } from '@wordpress/block-editor';
import { createElement } from '@wordpress/element';
import metadata from '${metadataImport}';

const TEMPLATE = ${JSON.stringify(template, null, 2)};
const TEMPLATE_LOCK = ${JSON.stringify(lock)};
const ALLOWED_BLOCKS = ${JSON.stringify(allowedBlocks, null, 2)};

function Edit() {
  return createElement(
    'div',
    useBlockProps(),
    createElement(InnerBlocks, {
      template: TEMPLATE,
      templateLock: TEMPLATE_LOCK,
      allowedBlocks: ALLOWED_BLOCKS,
    }),
  );
}

function Save() {
  return createElement('div', useBlockProps.save(), createElement(InnerBlocks.Content));
}

registerBlockType(metadata.name, { edit: Edit, save: Save });
`;
}

function styleSource(plan: AuthoringPlan): string {
  const selector = `.wp-block-${plan.target.name.replace('/', '-')}`;
  const mapped = plan.styles.outcomes
    .filter((outcome) => outcome.outcome === 'scoped-css')
    .map((outcome) => ` * ${outcome.property}: ${outcome.value ?? 'review required'}${outcome.reason ? ` (${outcome.reason})` : ''}`);
  return `${selector} {
  /* Scoped styles generated from the reviewed plan belong here. */
}
${mapped.length > 0 ? `\n/*\n${mapped.join('\n')}\n */\n` : ''}`;
}

function templateNode(node: AuthoringStructureNode): [string, Record<string, JsonValue>, Array<unknown>?] {
  const children = node.children?.map(templateNode);
  return children && children.length > 0
    ? [node.block, node.attributes ?? {}, children]
    : [node.block, node.attributes ?? {}];
}

function uniqueBlocks(nodes: AuthoringStructureNode[]): string[] {
  const blocks = new Set<string>();
  const visit = (node: AuthoringStructureNode): void => {
    blocks.add(node.block);
    node.children?.forEach(visit);
  };
  nodes.forEach(visit);
  return [...blocks].sort();
}
