import path from 'node:path';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import type { DestinationInspection } from './destination.js';
import type { GeneratedRegisteredBlock } from './generate.js';

/** The impact of replacing a compiler-owned package; never a claim to migrate a site. */
export type RegenerationImpactKind = 'new-package' | 'unchanged' | 'style-only' | 'content-defaults' | 'saved-markup-or-structure';

export interface RegenerationImpact {
  kind: RegenerationImpactKind;
  changedFiles: readonly string[];
  existingInstanceEffect: string;
  nextStep: string;
  writeAllowed: boolean;
}

const STYLE_FILES = new Set(['style.scss', 'editor.scss', 'font-licenses.txt']);
const NEW_INSTANCE_FILES = new Set(['edit.js', 'index.js', 'asset-urls.mjs']);
const SAVED_CONTENT_FILES = new Set(['save.js', 'block.json', 'block.php']);

/** Compare a reviewed destination snapshot with exact generated bytes. */
export async function classifyRegisteredBlockRegeneration(
  inspection: DestinationInspection,
  generated: GeneratedRegisteredBlock,
): Promise<RegenerationImpact> {
  const existing = new Map(inspection.entries
    .filter((entry) => entry.kind === 'file' && entry.identity?.sha256)
    .map((entry) => [entry.path, entry.identity!.sha256!] as const));
  const outputs = [...generated.files, ...generated.assets];
  const target = (file: { path: string }) => path.resolve(inspection.directory, ...file.path.split('/'));
  const knownExisting = outputs.some((file) => existing.has(target(file)));
  if (!knownExisting) return impact('new-package', [], 'No existing compiler-owned package was observed.', 'Review the create operations before writing.', true);

  const changedFiles = outputs.filter((file) => existing.get(target(file)) !== file.hash).map((file) => file.path).sort();
  if (changedFiles.length === 0) return impact('unchanged', changedFiles, 'Existing source and saved content remain unchanged.', 'No write is needed.', false);
  const structuralMetadata = changedFiles.includes('block.json') && !await hasOnlyDescriptiveMetadataChange(inspection, generated);
  if ((changedFiles.every((file) => STYLE_FILES.has(file)) || changedFiles.every((file) => STYLE_FILES.has(file) || file === 'block.json')) && !structuralMetadata) {
    return impact('style-only', changedFiles, 'Existing saved block markup is unchanged. Styles or referenced assets can still change the rendered appearance where this package is built and deployed.', 'Review the explicit replacements. This source change does not claim a sitewide pattern update.', true);
  }
  if (changedFiles.every((file) => STYLE_FILES.has(file) || NEW_INSTANCE_FILES.has(file) || file === 'block.json') && !structuralMetadata) {
    return impact('content-defaults', changedFiles, 'New insertions may use the updated editor template or assets. Existing saved block markup is unchanged, although existing editor UI behavior, styles, or assets can change when an instance is opened.', 'Review the explicit replacements and test the updated insertion path separately.', true);
  }
  const saved = changedFiles.filter((file) => SAVED_CONTENT_FILES.has(file) || (file === 'block.json' && structuralMetadata));
  const effect = saved.length
    ? 'Existing saved content can be affected by ' + saved.join(', ') + '; source regeneration does not migrate posts, templates, or synced patterns.'
    : 'The changed compiler-owned output has an unknown saved-content effect.';
  return impact('saved-markup-or-structure', changedFiles, effect, 'Use a new block identity, or add and pass a tested WordPress deprecation/migration before replacing this package.', false);
}

function impact(kind: RegenerationImpactKind, changedFiles: readonly string[], existingInstanceEffect: string, nextStep: string, writeAllowed: boolean): RegenerationImpact {
  return { kind, changedFiles, existingInstanceEffect, nextStep, writeAllowed };
}


async function hasOnlyDescriptiveMetadataChange(inspection: DestinationInspection, generated: GeneratedRegisteredBlock): Promise<boolean> {
  const next = generated.files.find((file) => file.path === 'block.json');
  const existing = inspection.entries.find((entry) => entry.path === path.resolve(inspection.directory, 'block.json') && entry.kind === 'file');
  if (!next || !existing?.identity?.sha256) return false;
  try {
    const bytes = await readFile(existing.path);
    if (createHash('sha256').update(bytes).digest('hex') !== existing.identity.sha256) return false;
    const before = JSON.parse(bytes.toString('utf8')) as Record<string, unknown>;
    const after = JSON.parse(next.content) as Record<string, unknown>;
    const descriptive = new Set(['title', 'description', 'category', 'icon', 'keywords']);
    const canonical = (value: unknown): string => JSON.stringify(value, (_key, item) => item && typeof item === 'object' && !Array.isArray(item)
      ? Object.fromEntries(Object.entries(item as Record<string, unknown>).sort(([left], [right]) => left.localeCompare(right)))
      : item);
    const operational = (value: Record<string, unknown>) => Object.fromEntries(Object.entries(value).filter(([key]) => !descriptive.has(key)));
    return canonical(operational(before)) === canonical(operational(after));
  } catch {
    return false;
  }
}
