export { canonicalize } from './gate/canonicalize.js';
export { validate } from './gate/validate.js';
export { convert } from './convert/assemble.js';
export { author } from './author/index.js';
export {
  compileTailwindBuildGraph,
  hasTailwindSignal,
  renderResidualCss,
  scanStylesheet,
  scopeLocalSelectorList,
  scopeStylesheet,
  validateCssBuildGraph,
} from './author/styles.js';
export type { CssBuildGraph, TailwindCompilation, TailwindCompilationOptions } from './author/styles.js';
export {
  classifyCssUrlReference,
  processCssAssets,
  rewriteCssAssets,
  scanCssUrlReferences,
} from './author/assets.js';
export { assemble, extractIntent, realize } from './intent/index.js';
export { compileAuthoringBlock, compileAuthoringPlan } from './authoring/compile.js';
export { collectSiteContext } from './context/run.js';
export {
  AUTHORING_PLAN_VERSION,
  AuthoringPlanValidationError,
  canonicalAuthoringPlanHash,
  canonicalAuthoringPlanJson,
  canonicalizeAuthoringPlan,
  hashAuthoringPlan,
  isSafeAuthoringRelativePath,
  serializeAuthoringPlan,
  validateAuthoringPlan,
} from './authoring/schema.js';
export {
  AuthoringGenerationError,
  GENERATED_REGISTERED_BLOCK_PATHS,
  REGISTERED_BLOCK_TEMPLATE_VERSION,
  WORDPRESS_BLOCK_SCHEMA_URL,
  WORDPRESS_BLOCK_SCHEMA_VERSION,
  compileRegisteredBlock,
  emitBlockJson,
  emitEditJs,
  emitIndexJs,
  emitPhp,
  emitSaveJs,
  emitScss,
  generateRegisteredBlock,
  materializeAuthoringPlan,
  planRegisteredBlockOutput,
  validateBlockMetadata,
  validateGeneratedSources,
} from './authoring/generate.js';
export { previewAuthoringPlan, renderAuthoringPreview } from './authoring/preview.js';
export { AuthoringStyleError, authoringRulesFromStylesheet, renderConfirmedStyleRules } from './authoring/styles.js';
export {
  hashAuthoringConfirmation,
  inspectAuthoringDestination,
  PublicationInterruptedError,
  recoverAuthoringPublication,
  retryAuthoringPublication,
  writeAuthoringOutput,
  writeGeneratedRegisteredBlock,
} from './authoring/destination.js';
export {
  assertStandaloneZipEntries,
  detectWpScriptsPlugin,
  planExistingPluginOutput,
  planStandalonePluginOutput,
  PublicationInterruptedError as PluginPublicationInterruptedError,
  recoverPluginPublication,
  retryPluginPublication,
  STANDALONE_LOCK_TEMPLATE_PACKAGE_COUNT,
  STANDALONE_LOCK_TEMPLATE_VERSION,
  STANDALONE_WP_SCRIPTS_VERSION,
  UnsupportedPluginLayoutError,
  WP_SCRIPTS_PROFILE,
  writePluginOutput,
} from './plugin/profile.js';
export type {
  GeneratedBlockPackage as PluginGeneratedBlockPackage,
  PluginFileContent,
  PluginFileOperation,
  PluginOutputPlan,
  PluginPlanMode,
  PluginProfile,
  PublicationRecovery as PluginPublicationRecovery,
  PublicationRecoveryEntry as PluginPublicationRecoveryEntry,
  PluginRegistrationStrategy,
  PluginTouchedFile,
  UnsupportedPluginProfile,
  WpScriptsPluginProfile,
  WritePluginOutputOptions,
  WritePluginOutputResult,
} from './plugin/profile.js';
export {
  runProof,
  prove,
} from './proof/runner.js';
export {
  PATTERN_OVERRIDE_SOURCE,
  applyPatternOverrides,
  patternOverrideName,
  supportedPatternOverrideAttributes,
} from './authoring/overrides.js';
export {
  patternOverrideContent,
  templateOverrideName,
  validatePatternOverrideContract,
} from './authoring/pattern-overrides.js';
export type { PatternOverrideBinding, PatternOverrideContract } from './authoring/pattern-overrides.js';
export {
  PROOF_GATE_IDS,
  PROOF_GATE_STATUSES,
  PROOF_PROFILE_NAMES,
  PROOF_PROFILES,
  canBeNotApplicable,
  createDefaultGateRecords,
  createDefaultProofGateRecords,
  evaluateProfile,
  evaluateProofProfile,
  evaluateProofProfiles,
  getProofProfile,
  isProofGateStatus,
  isProofProfileName,
  normalizeProofGateId,
  reportProofProfile,
} from './proof/profiles.js';
export {
  APPROVED_UPSTREAM_EXCEPTION_ID,
  APPROVED_UPSTREAM_PARAGRAPH_EXCEPTION_ID,
  evaluateReleaseAcceptance,
  loadNativeHeadingControlEvidence,
  loadNativeParagraphControlEvidence,
  summarizeReleaseAcceptance,
} from './proof/release-acceptance.js';
export type {
  AcceptedUpstreamFinding,
  NativeBlockControlEvidence,
  NativeHeadingControlEvidence,
  NativeParagraphControlEvidence,
  ReleaseAcceptanceBlocker,
  ReleaseAcceptanceOptions,
  ReleaseAcceptanceReport,
  ReleaseAcceptanceStatus,
} from './proof/release-acceptance.js';
export {
  EvidenceStore,
  ImmutableContentError,
  ReceiptWriter,
  canonicalJson,
  canonicalJsonStringify,
  hashCanonicalJson,
  sha256,
} from './proof/receipt.js';
export type { SiteContextOptions } from './context/run.js';
export type {
  AuthoringCssDeclaration,
  AuthoringCssRule,
  AuthoringAsset,
  AuthoringAssetStatus,
  AuthoringField,
  AuthoringFieldMode,
  AuthoringFile,
  AuthoringFileOperation,
  AuthoringLocking,
  AuthoringLockMode,
  AuthoringNodeLock,
  AuthoringPattern,
  AuthoringPatternOverride,
  AuthoringPlan as GeneratedAuthoringPlan,
  AuthoringCoverage,
  AuthoringCoverageAsset,
  AuthoringCoverageAssetOutcome,
  AuthoringCoverageLocation,
  AuthoringCoverageStyle,
  AuthoringCoverageStyleOutcome,
  AuthoringSource,
  AuthoringSourceFormat,
  AuthoringStructureNode,
  AuthoringStyleOutcome,
  AuthoringStyleOutcomeKind,
  AuthoringStyleStrategy,
  AuthoringStyles,
  AuthoringTarget,
  JsonPrimitive,
  JsonValue,
} from './authoring/schema.js';
export type { AuthoringPreviewContext, AuthoringPreviewOptions } from './authoring/preview.js';
export type {
  AuthoringDestinationApproval,
  AuthoringOutputFile,
  AuthoringOutputPlan,
  AuthoringPublicationOptions,
  DestinationEntry,
  DestinationInspection,
  PublicationRecovery,
  PublicationRecoveryEntry,
} from './authoring/destination.js';
export type {
  GeneratedRegisteredBlock,
  GeneratedSourceFile,
  GeneratedSourceKind,
  GeneratedSourceManifest,
  GeneratedSourceManifestEntry,
  GeneratedSourcePath,
  RegisteredBlockOutputPlan,
} from './authoring/generate.js';
export type {
  AssembleOptions,
  AuthoringDiagnostic,
  AuthoringEditableField,
  AuthoringNode,
  AuthoringPlan,
  AuthoringPlan as SemanticAuthoringPlan,
  AuthoringRole,
  AuthoringTemplate,
  AssetLedgerEntry,
  AssetOutcome,
  AuthoredStyleLedgerEntry,
  AuthoredStyleOutcome,
  AuthorConfig,
  AuthorOptions,
  AuthorStyleConfig,
  BlockRunnerConfig,
  BlockRunnerReport,
  CanonicalizeOptions,
  CommandName,
  CommonOptions,
  CompiledAuthoringBlock,
  ConvertOptions,
  IntentNode,
  IntentTree,
  InnerBlocksLock,
  GeneratedBlockPackage,
  MediaConfig,
  MediaMapEntry,
  MediaResult,
  MediaResolver,
  ReportItem,
  ReportStatus,
  ReportSummary,
  ResolvedTokens,
  ResolverKind,
  Rule,
  RuleContext,
  SourceLocation,
  StylingRung,
  TemplateLock,
  TokenConfig,
  TokenMatchMode,
  TokenResolver,
  TokenResolverKind,
  TailwindBuildGraph,
  TailwindCompiler,
  TailwindCompilerInput,
  ValidateOptions,
  WpBlock,
} from './types.js';
export type {
  ProofEditableField,
  ProofEditableSurface,
  ProofEnvironment,
  ProofFilePin,
  ProofFixture,
  ProofBrowserMatrix,
  ProofGateContext,
  ProofGateResult,
  ProofGateRunner,
  ProofCommandResult,
  ProofCommandOptions,
  ProofCommandRunner,
  ProofReceiptDocument,
  ProofRunOptions,
  ProofRunResult,
  WordPressPackagePin,
  ProofPatternInstance,
  ProofPatternNegativeBinding,
  ProofPatternRequiredBinding,
  PatternOverrideContent,
} from './proof/runner.js';
export type {
  GateId,
  GateRecord,
  GateStatus,
  ProfileName,
  ProofGateId,
  ProofGateOutcome,
  ProofGateRecord,
  ProofGateRecords,
  ProofGateStatus,
  ProofProfile,
  ProofProfileEvaluation,
  ProofProfileName,
  ProofProfileReport,
} from './proof/profiles.js';
export type {
  CanonicalJsonValue,
  ContentAddressedReference,
  EvidencePutOptions,
  EvidenceReference,
  HashInput,
  ProofReceipt,
  ReceiptReference,
  ReceiptWriteResult,
  Sha256,
} from './proof/receipt.js';
