import { assertSupportedNodeVersion } from './node-support.js';

// Assert before evaluating the implementation export graph and its production dependencies.
assertSupportedNodeVersion();
const library = await import('./index-implementation.js');

export const {
  APPROVED_UPSTREAM_EXCEPTION_ID,
  APPROVED_UPSTREAM_PARAGRAPH_EXCEPTION_ID,
  AUTHORING_PLAN_VERSION,
  AuthoringGenerationError,
  AuthoringPlanValidationError,
  AuthoringStyleError,
  EvidenceStore,
  GENERATED_REGISTERED_BLOCK_PATHS,
  ImmutableContentError,
  PATTERN_OVERRIDE_SOURCE,
  PROOF_GATE_IDS,
  PROOF_GATE_STATUSES,
  PROOF_PROFILES,
  PROOF_PROFILE_NAMES,
  REGISTERED_BLOCK_TEMPLATE_VERSION,
  ReceiptWriter,
  STANDALONE_LOCK_TEMPLATE_PACKAGE_COUNT,
  STANDALONE_LOCK_TEMPLATE_VERSION,
  STANDALONE_WP_SCRIPTS_VERSION,
  UnsupportedPluginLayoutError,
  WORDPRESS_BLOCK_SCHEMA_URL,
  WORDPRESS_BLOCK_SCHEMA_VERSION,
  WP_SCRIPTS_PROFILE,
  applyPatternOverrides,
  assemble,
  assertStandaloneZipEntries,
  author,
  authoringRulesFromStylesheet,
  canBeNotApplicable,
  canonicalAuthoringPlanHash,
  canonicalAuthoringPlanJson,
  canonicalJson,
  canonicalJsonStringify,
  canonicalize,
  canonicalizeAuthoringPlan,
  classifyCssUrlReference,
  collectSiteContext,
  collectSourceEvidence,
  compileAuthoringBlock,
  compileAuthoringPlan,
  compileRegisteredBlock,
  compileTailwindBuildGraph,
  convert,
  createDefaultGateRecords,
  createDefaultProofGateRecords,
  detectWpScriptsPlugin,
  emitBlockJson,
  emitEditJs,
  emitIndexJs,
  emitPhp,
  emitSaveJs,
  emitScss,
  evaluateProfile,
  evaluateProofProfile,
  evaluateProofProfiles,
  evaluateReleaseAcceptance,
  extractIntent,
  generateRegisteredBlock,
  getProofProfile,
  hasTailwindSignal,
  hashAuthoringConfirmation,
  hashAuthoringPlan,
  hashCanonicalJson,
  inspectAuthoringDestination,
  isProofGateStatus,
  isProofProfileName,
  isSafeAuthoringRelativePath,
  loadNativeHeadingControlEvidence,
  loadNativeParagraphControlEvidence,
  materializeAuthoringPlan,
  normalizeProofGateId,
  patternOverrideContent,
  patternOverrideName,
  planExistingPluginOutput,
  planRegisteredBlockOutput,
  planStandalonePluginOutput,
  previewAuthoringPlan,
  processCssAssets,
  prove,
  realize,
  renderAuthoringPreview,
  renderConfirmedStyleRules,
  renderResidualCss,
  reportProofProfile,
  rewriteCssAssets,
  runProof,
  scanCssUrlReferences,
  scanStylesheet,
  scopeLocalSelectorList,
  scopeStylesheet,
  serializeAuthoringPlan,
  sha256,
  summarizeReleaseAcceptance,
  supportedPatternOverrideAttributes,
  templateOverrideName,
  validate,
  validateAuthoringPlan,
  validateBlockMetadata,
  validateCssBuildGraph,
  validateGeneratedSources,
  validatePatternOverrideContract,
  writeAuthoringOutput,
  writeGeneratedRegisteredBlock,
  writePluginOutput,
} = library;

export type * from './index-implementation.js';

export type AuthoringGenerationError = import('./index-implementation.js').AuthoringGenerationError;
export type AuthoringPlanValidationError = import('./index-implementation.js').AuthoringPlanValidationError;
export type AuthoringStyleError = import('./index-implementation.js').AuthoringStyleError;
export type EvidenceStore = import('./index-implementation.js').EvidenceStore;
export type ImmutableContentError = import('./index-implementation.js').ImmutableContentError;
export type ReceiptWriter = import('./index-implementation.js').ReceiptWriter;
export type UnsupportedPluginLayoutError = import('./index-implementation.js').UnsupportedPluginLayoutError;
